---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: trapps-web-source

outputs:
- name: package-output

run:
  path: trapps-web-source/ci/tasks/deploy.sh
