---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: trapps-web-source

outputs:
- name: package-output

run:
  path: trapps-web-source/ci/tasks/deploy2.sh
