---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

inputs:
- name: trapps-web-source

outputs:
- name: dist

run:
  path: trapps-web-source/ci/tasks/deploy.sh
