platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
  - name: trapps-web-source
run:
  path: trapps-web-source/ci/tasks/npm-install.sh