---
resources:
- name: trapps-web-source
  type: git
  source:
    uri: https://github.com/insys-group/trapps-web.git
    branch: feature/concourse
- name: cf-deploy
  type: cf
  source:
    buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
    api: {{pcf-api}}
    username: {{pcf-user}}
    password: {{pcf-pwd}}
    organization: {{pcf-org}}
    space: {{pcf-space}}
    skip_cert_check: true

jobs:
- name: build-and-deploy
  public: true
  plan:
  - get: trapps-web-source
    trigger: true
  - task: npm
    file: trapps-web-source/ci/tasks/deploy.yml
#  - task: npm
#    file: trapps-web-source/ci/tasks/npm-install.yml
  - put: cf-deploy
    params:
      manifest: trapps-web-source/manifest.yml
      path: dist/