---
resources:
- name: trapps-web-source
  type: git
  source:
    uri: https://github.com/insys-group/trapps-web.git
    branch: feature/concourse

jobs:
- name: repo
  public: true
  plan:
  - get: trapps-web-source
    trigger: true
  - task: package
    file: trapps-web-source/ci/tasks/build.yml
